alex_alex_homepage:
    path:  /hello/{name}
    defaults: { _controller: AlexAlexBundle:Default:index }

flights:
    path:      /SearchFlightsByDate
    defaults:  { _controller: AlexAlexBundle:Default:searchFlights }