parameters:
#    alex_alex.example.class: Alex\AlexBundle\Example

services:
#    alex_alex.example:
#        class: %alex_alex.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
