parameters:
    alex_alex.flightSearchService.class: Alex\AlexBundle\SearchServices\FlightSearchService

services:
    alex_alex.flightSearchService:
        class: %alex_alex.flightSearchService.class%
        arguments: [@service_container]
